CREATE DATABASE DirectoryDB
GO
Use DirectoryDB;

CREATE TABLE CUSTOMER(
	CUSTOMER_ID int IDENTITY (1, 1) PRIMARY KEY,
	CUSTOMER_NAME varchar (100) NOT NULL,
	INN varchar (12) NOT NULL,
	ADDRESS varchar (255)
)

CREATE TABLE ACCOUNT(
	ACCOUNT_ID int IDENTITY (1, 1),
	CUSTOMER_ID int NOT NULL,
	ACCOUNT_NUMBER varchar (20) NOT NULL,
	ACCOUNT_NAME varchar (100),
	BIC varchar (9) NOT NULL,
	ACCOUNT_BALANCE decimal (14, 2) NOT NULL
);